export enum ColumnPricingToUpdate {
    ALL = "ALL",
    TARIFF = "TARIFF",
    INSURANCE = "INSURANCE",
    HOME_DELIVERY = "HOME_DELIVERY",
    HOME_WITHDRAWAL = "HOME_WITHDRAWAL",
    OTHERS = "OTHERS",
    TARIFF_INCREASE = "TARIF_INCREASE",
    ADDITIONAL_INCREASE = "ADDITIONAL_INCREASE"
}
